service: tokenization
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    REDIS_PASSWORD: ${env:REDIS_PASSWORD}

functions:
  tokenize:
    handler: src/handlers/tokenizeHandler.handler
    events:
      - httpApi:
          path: /tokenize
          method: post
  token:
    handler: src/handlers/getTokenHandler.handler
    events:
      - httpApi:
          path: /token/{token}
          method: get

plugins:
  - serverless-offline
  - serverless-esbuild
